### ISSUE TITLE
[Bug] Python3 Miniedit import export file

### ISSUE THREAD

**Issue by lorenzomonta** [mininet/mininet#1049]
Running the command: `sudo HOME=~ python3 -m mininet.examples.miniedit` and try to import or export a topology or export the Python script, both files are empty. If you run the command: `sudo HOME=~ python2 -m mininet.examples.miniedit` this doesn't happen. Everything works correctly.

```
mininet@mininet-vm:~$ sudo HOME=~ python3 -m mininet.examples.miniedit
debug1: client_input_channel_open: ctype x11 rchan 2 win 65536 max 16384
debug1: client_request_x11: request from 127.0.0.1 35858
debug1: x11_connect_display: $DISPLAY is launchd
debug1: channel 1: new [x11]
debug1: confirm x11
topo=none
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.8/dist-packages/mininet/examples/miniedit.py", line 1452, in loadTopology
    self.appPrefs = dict(self.appPrefs.items() + loadedTopology['application'].items())
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'
```

**Comment by Nelson-iitp** [comment]
for saving error in .py file
https://github.com/mininet/mininet/issues/1086#issuecomment-2094575074

for loading error in .mn files
https://github.com/mininet/mininet/issues/1214#issuecomment-2094577488
