### ISSUE TITLE
encounter error 'invalid version number'

### ISSUE THREAD

**Issue by Wu-XinYuan** [mininet/mininet#1094]
When running `\examples\miniedit.py` and try to export the level 2 script with mininet version 2.0.3.dev6, I encountered the following error:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "miniedit.py", line 1713, in exportScript
    if StrictVersion(MININET_VERSION) > StrictVersion('2.0'):
  File "/usr/lib/python3.8/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python3.8/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '2.3.0.6'
```

I found the related code to generate this invalid version number is in `line 81`  in `miniedit.py`:
```
MININET_VERSION = re.sub(r'[^\d\.]', '', VERSION)
```
thus changing `2.3.0.dev6` into `2.3.0.6` but not `2.3.0`, which is an invalid input for function `StrictVersion()`

**Comment by janev94** [comment]
@Wu-XinYuan the dev and rc releases are not endorsed for public use, these often contain new or not tested features. Please refrain from using any of these in case you are not a contributor and use one of the official versions such as the latest one as of the time of writing this - [2.3.0](https://github.com/mininet/mininet/tree/2.3.0).

@lantz consider closing this. Not sure if the regex should be fixed as my understanding is that we do not expect everything to be working under these releases.

**Comment by lantz** [comment]
Reopening - current master is supposed to be usable and we want to fix this for 2.3.1.

**Comment by badcodebuilder** [comment]
So did I. To deal with this problem, I removed all content after [PATCH version](https://semver.org/#summary)

From:
https://github.com/mininet/mininet/blob/6eb8973c0bfd13c25c244a3871130c5e36b5fbd7/examples/miniedit.py#L80
To
`MININET_VERSION = re.sub(r'[^\d\.]', '', "".join(VERSION.split(".")[:3]))`

And it worked.
