### ISSUE TITLE
Can't connect remote controller using IPv6 address

### ISSUE THREAD

**Issue by rezaainur** [mininet/mininet#1132]
### Expected/Desired Behavior:
Connect remote controller using IPv6 address.

### Actual Behavior:
Can't start the topology using IPv6 for remote controller.
If I use command in CLI, with `--controller=remote,ip=[ipv6_address]`, it says:
```
Caught exception. Cleaning up...

ValueError: too many values to unpack
```
but if I enter ipv6 address inside the python file, in `net.addController` method, and run the file with `sudo python [file_name.py]` it says:
```
*** Adding controller
Traceback (most recent call last):
  File "custom_topology2.py", line 80, in <module>
    myNetwork()
  File "custom_topology2.py", line 25, in myNetwork
    port=6633)
  File "/usr/local/lib/python2.7/dist-packages/mininet/net.py", line 291, in addController
    controller_new = controller( name, **params )
  File "/usr/local/lib/python2.7/dist-packages/mininet/node.py", line 1540, in __init__
    Controller.__init__( self, name, ip=ip, port=port, **kwargs )
  File "/usr/local/lib/python2.7/dist-packages/mininet/node.py", line 1410, in __init__
    ip, port = ip.split( ':' )
ValueError: too many values to unpack
```
 
### Detailed Steps to Reproduce the Behavior:
`sudo mn --controller=remote,ip=[ipv6_address] --switch ovs,protocols=OpenFlow13`
`sudo python [file_name.py]`

### Additional Information:
Based on error after run python file, we can see maybe Mininet recognize colon (:) to separate bit fields in IPv6 address, as the splitter between ip address (IPv4) with port number.
Is there any way to connect the remote controller using IPv6 address in Mininet?
I search this issue over the internet but can't find the answer yet.
I use Mininet 2.3.0 and ONOS controller 2.7.0.
Thank you for your answer.

**Comment by rezaainur** [comment]
Update:
I realized the `ValueError: too many values to unpack` error is because `ip.split()` failed to split IPv6 address with port number to `ip` and `port` variable because there was too much colon in IPv6 address. I tried to modify the `node.py` file in line 1410 as shown in error before.

I assume the `ip` variable is the joined IP address and port number of the controller (ex: 192.168.56.101:6653 or 2001::1:6653). I add some code to separate the last string which is the port number, with reverse the string  (ex: 2001::1:6653 to 3566:1::1002), then do `ip.split()` and add max split number parameter with 1, so the code just split the port number (first string before the first colon) with IPv6 address. After that I reverse the string again and we have the correct IPv6 address and port number (ex: 2001::1 and 6653).

Code before:
```
if ':' in ip:
    ip, port = ip.split( ':' )
    port = int( port )
self.ip = ip
self.port = port
```
Code after:
```
if ':' in ip:
    ip = ip[::-1]
    port, ip = ip.split( ':', 1 )
    ip = ip[::-1]
    port = port[::-1]
    port = int( port )
self.ip = ip
self.port = port
```
I managed to run my custom topology, but it says Mininet can't connect to the remote controller at IP destination, and I think because the port number is missing because:

- When I use IPv4:
`Unable to contact the remote controller at 192.168.56.106:6633`
  Mininet dump command:
`<RemoteController c0: 192.168.56.101:6633 pid=5002>`

- When I use IPv6:
`Unable to contact the remote controller at 2001:db8:1212::1111`
  Mininet dump command:
`<RemoteController c0: 2001:db8:1212::1111 pid=6022>`

The port number is missing when I use IPv6 address, but I don't know what causes this. When I use IPv4, Mininet just working correctly and the host can ping each other.
Any suggestions for this issue?
I appreciate for your answer, thank you so much.
