### ISSUE TITLE
Long hostnames leads to interfaces names too long

### ISSUE THREAD

**Issue by sargonphin** [mininet/mininet#1133]
### Expected/Desired Behavior:
Adding a host with a long hostname (for example: SW_SUPERVISOR_1) creates an interface with the name and ethx appended to it (for example: SW_SUPERVISOR_1-eth5)

### Actual Behavior:
Hosts with long hostnames generates long interface names which raises an exception in the interface creation. 

```
(P4_5, SW_RED_5) *** SW_SUPERVISOR_1 : ('ip link add name SW_SUPERVISOR_1-eth5 address 9a:da:df:3c:03:15 type veth peer name SRV_BLCK_1-eth0 address 62:96:25:5c:29:7f netns 5033',)

Error: argument "SW_SUPERVISOR_1-eth5" is wrong: "name" not a valid ifname

Traceback (most recent call last):
  File "/mininet/testTopology.py", line 101, in <module>
    initTopology()
  File "/mininet/testTopology.py", line 94, in initTopology
    network = Mininet(topo, switch=OVSKernelSwitch)
  File "/usr/lib/python3/dist-packages/mininet/net.py", line 178, in __init__
    self.build()
  File "/usr/lib/python3/dist-packages/mininet/net.py", line 508, in build
    self.buildFromTopo( self.topo )
  File "/usr/lib/python3/dist-packages/mininet/net.py", line 495, in buildFromTopo
    self.addLink( **params )
  File "/usr/lib/python3/dist-packages/mininet/net.py", line 406, in addLink
    link = cls( node1, node2, **options )
  File "/usr/lib/python3/dist-packages/mininet/link.py", line 456, in __init__
    self.makeIntfPair( intfName1, intfName2, addr1, addr2,
  File "/usr/lib/python3/dist-packages/mininet/link.py", line 501, in makeIntfPair
    return makeIntfPair( intfname1, intfname2, addr1, addr2, node1, node2,
  File "/usr/lib/python3/dist-packages/mininet/util.py", line 270, in makeIntfPair
    raise Exception( "Error creating interface pair (%s,%s): %s " %
Exception: Error creating interface pair (SW_SUPERVISOR_1-eth5,SRV_BLCK_1-eth0): Error: argument "SW_SUPERVISOR_1-eth5" is wrong: "name" not a valid ifname
```

### Detailed Steps to Reproduce the Behavior:
1. Add two hosts, one with a long hostname

```
hta = addHost('HT_LONGHOSTNAME_1')
htb = addHost('HT_2')
```

2. Create links between these hosts

```
net.addLink(swa,swb)
```

3. Initialize network

### Additional Information:

--

**Comment by clnhlzmn** [comment]
Is there any workaround for this?

**Comment by alexpyattaev** [comment]
you'd need to rewrite linux kernel. There can not be a fix in mininet.
