### ISSUE TITLE
mininet/examples/limit.py cannot be run when not using VM

### ISSUE THREAD

**Issue by heryandi** [mininet/mininet#141]
The limit.py example cannot be run if I am not using the provided VM.
The mininet version I used is 2.0.0, the one available from Ubuntu 12.04 backports repository.

Below is the error message:
**\* Testing with rt bandwidth limiting
**\* Creating network
**\* Adding controller
**\* Adding hosts:
Traceback (most recent call last):
  File "./limit.py", line 53, in <module>
    limit()
  File "./limit.py", line 30, in limit
    net = Mininet( topo=myTopo, intf=intf, host=host )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 163, in **init**
    self.build()
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 315, in build
    self.buildFromTopo( self.topo )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 289, in buildFromTopo
    self.addHost( hostName, *_topo.nodeInfo( hostName ) )
  File "/usr/lib/python2.7/dist-packages/mininet/net.py", line 185, in addHost
    h = cls( name, *_defaults )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 406, in customized
    return cls( _args, *_kwargs )
  File "/usr/lib/python2.7/dist-packages/mininet/node.py", line 567, in **init**
    errFail( 'cgcreate -g ' + self.cgroup )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 109, in errFail
    out, err, ret = errRun( _cmd, *_kwargs )
  File "/usr/lib/python2.7/dist-packages/mininet/util.py", line 77, in errRun
    popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by cheriimoya** [comment]
i guess this can be closed
