### ISSUE TITLE
Exception: cgroups not mounted on /sys/fs/cgroup

### ISSUE THREAD

**Issue by DamianSheldon** [mininet/mininet#469]
Hi,

I start mininet encounter this error, my OS is ubuntu 14.04.

meiliang@meiliang-VirtualBox:~/cs144_security$ ./run.sh 
start cs144 buffer bloat experiment
starting mininet ....
Traceback (most recent call last):
  File "macoverflow.py", line 67, in <module>
    bbnet()
  File "macoverflow.py", line 51, in bbnet
    autoPinCpus=True)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 160, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 308, in build
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 282, in buildFromTopo
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 182, in addHost
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 556, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 704, in init
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 365, in mountCgroups
Exception: cgroups not mounted on /sys/fs/cgroup
cleaning up...
tcpdump: no process found
ping: no process found
end

**Comment by lantz** [comment]
1. You haven't provided enough information to reproduce your problem.

2. What happened when you tried to fix the problem as suggested?

**Comment by DamianSheldon** [comment]
I just follow the environment setup guide, execute ./run.sh log this error.
----- 原始邮件 -----
发件人：lantz <notifications@github.com>
收件人：mininet/mininet <mininet@noreply.github.com>
抄送人：Meiliang Dong <dongmeilianghy@sina.com>
主题：Re: [mininet] Exception: cgroups not mounted on /sys/fs/cgroup (#469)
日期：2015年01月23日 07点23分


You haven't provided enough information to reproduce your problem.
What happened when you tried to fix the problem as suggested?


&mdash;

**Comment by lantz** [comment]
1. Please provide the **complete, extremely detailed set of steps to reproduce the problem**.

2. Please confirm that you have **read and understood the error message and attempted to fix the problem by mounting `/sys/fs/cgroup`**

**Comment by DamianSheldon** [comment]
meiliang@meiliang-VirtualBox:~/cs144_security$ ls /sys/fs/cgroup/
blkio/      cpuacct/    devices/    hugetlb/    perf_event/ 
cpu/        cpuset/     freezer/    memory/     systemd/

According to above contents, I think cgroups was mounted successfully! But the issue is still here.

Following is my steps:

1, install a ubuntu 14.04 on virtualbox;
2, follow Mac address table overflow attack
    a,Environment Setup;
    b,Check Out Starter Code;
    c,Link POX into the Directory;
    d,Configure the Environment;
    e,Start POX Network Controller;
    f,Start Mininet Emulation
just this step:
meiliang@meiliang-VirtualBox:~/cs144_security$ ./run.sh
start cs144 buffer bloat experiment
starting mininet ....
Traceback (most recent call last):
File "macoverflow.py", line 67, in
bbnet()
File "macoverflow.py", line 51, in bbnet
autoPinCpus=True)
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 160, in init
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 308, in build
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 282, in buildFromTopo
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 182, in addHost
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 556, in init
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 704, in init
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 365, in mountCgroups
Exception: cgroups not mounted on /sys/fs/cgroup
cleaning up...
tcpdump: no process found
ping: no process found
end

My virtualbox version is 4.3.16 r95972

**Comment by lantz** [comment]
@DamianSheldon You still have not provided enough detail (for example: what were the commands you used to set up your environment? what were the commands to configure it? what version of Mininet are you using? where did you get it from? how did you install it? where did you get the experiment code from? etc.)

**Comment by DamianSheldon** [comment]
Ok, Let me describe more detail,

1,VirtualBox, Ubuntu14.04 are downloading from office website, virtualbox version is 4.3.16 r95972
2,Install Needed Tools
sudo apt-get update
sudo apt-get install -y git vim-nox python-setuptools libpython-all-dev flex bison traceroute

3,Install Mininet
cd ~
git clone git://github.com/mininet/mininet
cd mininet
./util/install.sh -fnv

4,Install POX
cd ~
git clone http://github.com/noxrepo/pox

5,Install ltprotocol
cd ~
git clone git://github.com/dound/ltprotocol.git
cd ltprotocol 
sudo python setup.py install

6,~$ cd ~
~$ git clone https://huangty@bitbucket.org/huangty/cs144_security.git
~/cs144_security$ cd cs144_security/

7,~/cs144_security$ ln -s ~/pox/

8,~/cs144_security$ bash ./config.sh

9,~/cs144_security$ ./run_pox.sh

10,~/cs144_security$ ./run.sh

meiliang@meiliang-VirtualBox:~/cs144_security$ ./run.sh
start cs144 buffer bloat experiment
starting mininet ....
Traceback (most recent call last):
File "macoverflow.py", line 67, in
bbnet()
File "macoverflow.py", line 51, in bbnet
autoPinCpus=True)
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 160, in init
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 308, in build
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 282, in buildFromTopo
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 182, in addHost
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 556, in init
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 704, in init
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 365, in mountCgroups
Exception: cgroups not mounted on /sys/fs/cgroup
cleaning up...
tcpdump: no process found
ping: no process found
end

11, apt-cache search cgroup

12,sudo apt-get cgroup-bin libcgroup1

13, meiliang@meiliang-VirtualBox:~/cs144_security$ ls /sys/fs/cgroup/
blkio/ cpuacct/ devices/ hugetlb/ perf_event/ 
cpu/ cpuset/ freezer/ memory/ systemd/

14, meiliang@meiliang-VirtualBox:~/cs144_security$ ./run.sh
start cs144 buffer bloat experiment
starting mininet ....
Traceback (most recent call last):
File "macoverflow.py", line 67, in
bbnet()
File "macoverflow.py", line 51, in bbnet
autoPinCpus=True)
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 160, in init
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 308, in build
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 282, in buildFromTopo
File "build/bdist.linux-x86_64/egg/mininet/net.py", line 182, in addHost
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 556, in init
File "build/bdist.linux-x86_64/egg/mininet/node.py", line 704, in init
File "build/bdist.linux-x86_64/egg/mininet/util.py", line 365, in mountCgroups
Exception: cgroups not mounted on /sys/fs/cgroup
cleaning up...
tcpdump: no process found
ping: no process found
end
