### ISSUE TITLE
Circular import problem with the Node and Link modules.

### ISSUE THREAD

**Issue by matanby** [mininet/mininet#546]
There seem to be a circular import between the node.py and link.py modules:
link.py:29 -> `import mininet.node`
node.py:67 -> `from mininet.link import Link, Intf, TCIntf, OVSIntf`

Which causes an ImportError when trying to import the link module first:

```
>>> import mininet.link
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/mininet/.pycharm_helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 29, in <module>
  File "/home/mininet/.pycharm_helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 67, in <module>
ImportError: cannot import name Link
```

A simple workaround is to import the node module before importing the link module. e.g:

```
import miniet.node
import mininet.link
```

**Comment by josiahls** [comment]
Same issue for me, pretty major since without the above hack I cant test bandwidth easily.

**Comment by matanby** [comment]
Fixed in https://github.com/khaled3ttia/mininetExp/commit/2fda4f25f0a73b2ed922fe9b9bcc50d63335e94f
