### ISSUE TITLE
Timeout in testPingKernel

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#655]
This is strange - is there some sort of race condition?

```
======================================================================  
ERROR: testPingKernel (test_scratchnet.testScratchNet)  
----------------------------------------------------------------------  
Traceback (most recent call last):  
  File "/home/mininet/mininet/examples/test/test_scratchnet.py", line 21, in testPingKernel  
    self.pingTest( 'mininet.examples.scratchnet' )  
  File "/home/mininet/mininet/examples/test/test_scratchnet.py", line 17, in pingTest  
    index = p.expect( self.opts )  
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1418, in expect  
    timeout, searchwindowsize)  
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1433, in expect_list  
    timeout, searchwindowsize)  
  File "/usr/lib/python2.7/dist-packages/pexpect/__init__.py", line 1535, in expect_loop  
    raise TIMEOUT(str(err) + '\n' + str(self))  
TIMEOUT: Timeout exceeded.  
<pexpect.spawn object at 0x7fa8ed81ff90>  
version: 3.1  
command: /usr/bin/python  
args: ['/usr/bin/python', '-m', 'mininet.examples.scratchnet']  
searcher: <pexpect.searcher_re object at 0x7fa8ed81ff10>  
buffer (last 100 chars): '0\r\nh1\r\n*** Starting network using Open vSwitch\r\n\r\n\r\n*** Waiting for switch to connect to controller.'  
before (last 100 chars): '0\r\nh1\r\n*** Starting network using Open vSwitch\r\n\r\n\r\n*** Waiting for switch to connect to controller.'  
after: <class 'pexpect.TIMEOUT'>  
match: None  
match_index: None  
exitstatus: None  
flag_eof: False  
pid: 23413  
child_fd: 6  
closed: False  
timeout: 30  
delimiter: <class 'pexpect.EOF'>  
logfile: None  
logfile_read: None  
logfile_send: None  
maxread: 2000  
ignorecase: False  
searchwindowsize: None  
delaybeforesend: 0.05  
delayafterclose: 0.1  
delayafterterminate: 0.1  
  
----------------------------------------------------------------------  
Ran 39 tests in 699.170s  
  
FAILED (errors=1, skipped=1) 
```

**Comment by lantz** [comment]
I believe the problem was with a prior test which was affecting this one.
