### ISSUE TITLE
Installation script is not fully working.

### ISSUE THREAD

**Issue by castroflavio** [mininet/mininet#669]
The mininet installation script is not fully working. Specifically the RYU installation is not working.

I get this error: 

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '\\')

Storing debug log for failure in /root/.pip/pip.log

**Comment by lantz** [comment]
Thanks @castroflavio - do you have a fix for this?

**Comment by lantz** [comment]
Seems to be a problem in Ubuntu 16 only - but both `pip install` and `setup.py install` work out of the box in Ubuntu 16 - the other stuff only seems to be needed for earlier versions.

**Comment by leonardodavila** [comment]
You should do sudo pip install .

**Comment by cheriimoya** [comment]
the log says `python2.7`, i don't think python2 is supported anymore, is it?
