### ISSUE TITLE
OVS Switch batch shutdown crashes when used with Floodlight

### ISSUE THREAD

**Issue by adipon** [mininet/mininet#724]
### Expected/Desired Behavior:
Switches should be shutdown on call to net.stop() without any errors and open port connections with ovs-vsctrl should be cleaned up.

### Actual Behavior:
The error below is thrown indicating that the switches could not be unregistered from the ovsdb. Mininet then requires a manual cleanup to close the open connections (ie. sudo mn -c). It appears that the error occurs because the clean up command for the ovsdb is not being done through a shell. The batchStartup method does use a shell when it initializes the database entries. 

  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 522, in stop
    success = swclass.batchShutdown( switches )
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 1237, in batchShutdown
    ' -- '.join( delcmd % s for s in switches ) )
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 83, in errRun
    popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception

### Detailed Steps to Reproduce the Behavior:
Within a python script, create a Mininet network with 3 or more OVSSwitches in a star topology using the Floodlight controller. Execute the net.stop() command and the above error will be reported. The switches will be reported as still active when using ovs-vsctrl as well. 

### Additional Information:
Proposed solution that has worked for me is to update Mininet/node.py such that the OVSSwitch.batchShutdown(...) method replaces line 1236-1237 with the following:

run( 'ovs-vsctl ' + ' -- '.join( delcmd % s for s in switches ) , shell=True)

**Comment by lantz** [comment]
I tried to reproduce this and it seems to work fine:

```python
from mininet.net import Mininet
from mininet.topo import SingleSwitchTopo
from mininet.log import setLogLevel
setLogLevel( 'info' )
net = Mininet( topo=SingleSwitchTopo( 5 ) )
net.start()
net.pingAll()
net.stop()
```

Here is the output:

```
sudo python test.py
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 h3 h4 h5 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) (h3, s1) (h4, s1) (h5, s1) 
*** Configuring hosts
h1 h2 h3 h4 h5 
*** Starting controller
c0 
*** Starting 1 switches
s1 ...
*** Ping: testing ping reachability
h1 -> h2 h3 h4 h5 
h2 -> h1 h3 h4 h5 
h3 -> h1 h2 h4 h5 
h4 -> h1 h2 h3 h5 
h5 -> h1 h2 h3 h4 
*** Results: 0% dropped (20/20 received)
*** Stopping 1 controllers
c0 
*** Stopping 5 links
.....
*** Stopping 1 switches
s1 
*** Stopping 5 hosts
h1 h2 h3 h4 h5 
*** Done
```

**Comment by roganartu** [comment]
This is caused by unicode switch names.

Here's a modified version of your example @lantz that triggers this:
```
#!/usr/bin/env python
from __future__ import absolute_import
from __future__ import unicode_literals

from mininet.log import setLogLevel
from mininet.net import Mininet
from mininet.topo import SingleSwitchTopo

def main():
    setLogLevel('info')
    net = Mininet(topo=SingleSwitchTopo(5))
    net.switches[0].name = 's1'
    net.start()
    net.pingAll()
    net.stop()

if __name__ == '__main__':
    main()
```
produces:
```
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 h3 h4 h5
*** Adding switches:
s1
*** Adding links:
(h1, s1) (h2, s1) (h3, s1) (h4, s1) (h5, s1)
*** Configuring hosts
h1 h2 h3 h4 h5
*** Starting controller
c0
*** Starting 1 switches
s1 ...
*** Ping: testing ping reachability
h1 -> h2 h3 h4 h5
h2 -> h1 h3 h4 h5
h3 -> h1 h2 h4 h5
h4 -> h1 h2 h3 h5
h5 -> h1 h2 h3 h4
*** Results: 0% dropped (20/20 received)
*** Stopping 1 controllers
c0
*** Stopping 5 links
.....
*** Stopping 1 switches
Traceback (most recent call last):
  File "bad.py", line 18, in <module>
    main()
  File "bad.py", line 15, in main
    net.stop()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 582, in stop
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 1254, in batchShutdown
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 83, in errRun
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Notice the `unicode_literals` import. To fix the example snippet either remove that import, remove the `net.switches[0].name = 's1'` line, or pass a native string instead.

The accepted py2/3 compatible way to get native strings when using unicode_literals is the following:
```
>>> from future.utils import bytes_to_native_str as n

>>> s = n(b'ABCD')
```
from http://python-future.org/unicode_literals.html

If you set the log level to `'debug'` you can see the difference in commands passed to `run` (and it becomes obvious why passing `shell=True` fixes the problem.
Working:
```
*** Stopping 1 switches
*** errRun: ['ovs-vsctl', '--if-exists', 'del-br', 's1']
```
Broken:
```
*** Stopping 1 switches
*** errRun: ovs-vsctl --if-exists del-br s1
Traceback (most recent call last):
  File "bad.py", line 18, in <module>
    main()
  File "bad.py", line 15, in main
    net.stop()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 582, in stop
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 1254, in batchShutdown
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 83, in errRun
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The problem section from `batchShutdown` above:
```
run( 'ovs-vsctl ' +
     ' -- '.join( delcmd % s for s in switches ) )
```
Which ends up running:
```
# Allow passing in a list or a string
if isinstance( cmd, str ) and not shell:
    cmd = cmd.split( ' ' )
    cmd = [ str( arg ) for arg in cmd ]
elif isinstance( cmd, list ) and shell:
    cmd = " ".join( arg for arg in cmd )
debug( '*** errRun:', cmd, '\n' )
popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
```

Mininet is attempting to execute a file called `ovs-vsctl --if-exists del-br s1` instead of `ovs-vsctl` with args `--if-exists del-br s1`, hence the `OSError: [Errno 2] No such file or directory`.

fwiw an (untested) easy fix for this might even just be to use [`shlex.split()`](https://docs.python.org/2/library/shlex.html#shlex.split):
```
# Allow passing in a list or a string
if isinstance( cmd, list ):
    if shell:
        cmd = " ".join( arg for arg in cmd )
elif not shell:
    cmd = shlex.split(cmd)
debug( '*** errRun:', cmd, '\n' )
popen = Popen( cmd, stdout=PIPE, stderr=stderr, shell=shell )
```
You'd also get the benefit of using a more robust lexer than simple string splitting.
