### ISSUE TITLE
Unicode Switch Names Break Cleanup

### ISSUE THREAD

**Issue by bradmwalker** [mininet/mininet#739]
### Expected/Desired Behavior:

Mininet cleans network interfaces, switches, and shell child processes upon exiting interactive mode.

### Actual Behavior:

After exiting interactive mode, Mininet crashes with a traceback (below). Switches, interfaces, and orphaned processes remain.

```
*** Starting CLI:
mininet> 
*** Stopping 1 controllers
c0 
*** Stopping 6 links
......
*** Stopping 3 switches
Traceback (most recent call last):
  File "linuxrouter.py", line 91, in <module>
    run()
  File "linuxrouter.py", line 87, in run
    net.stop()
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 582, in stop
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 1253, in batchShutdown
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 83, in errRun
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

### Detailed Steps to Reproduce the Behavior:

Edit the linuxrouter example and make the switch nodes' names unicode:

```
diff --git a/examples/linuxrouter.py b/examples/linuxrouter.py
index a7e312b..9c91db6 100755
--- a/examples/linuxrouter.py
+++ b/examples/linuxrouter.py
@@ -56,7 +56,7 @@ def build( self, **_opts ):
         defaultIP = '192.168.1.1/24'  # IP address for r0-eth1
         router = self.addNode( 'r0', cls=LinuxRouter, ip=defaultIP )
 
-        s1, s2, s3 = [ self.addSwitch( s ) for s in ( 's1', 's2', 's3' ) ]
+        s1, s2, s3 = [ self.addSwitch( s ) for s in ( u's1', u's2', u's3' ) ]
 
         self.addLink( s1, router, intfName2='r0-eth1',
                       params2={ 'ip' : defaultIP } )  # for clarity
``` 
### Additional Information:

This can be hit inadvertently with `from __future__ import unicode_literals`.

One unicode switch name will coerce the `ov-vsctl del-br` command into a unicode string. The tokenizing code in errRun (util.py:77) doesn't tokenize a unicode string. The unicode string gets passed to Popen as the command, which will either give a "No such fire or directory" OSError or a "File name too long" OSError, depending on number of switches.

**Comment by cheriimoya** [comment]
actually, with python3 having full utf8 support, this is solved.
