### ISSUE TITLE
Unable to connect two ports of the same switch with .addLink() method - RTNETLINK answers: File exists

### ISSUE THREAD

**Issue by ongrid** [mininet/mininet#750]
Unable to connect two ports of the same switch (port-to-port patchcord emulation)

### Expected/Desired Behavior:
Such a topology with link attached to ports of the same switch is common in networking and should be possible to run.
```
class PatchTopo( Topo ):
    def __init__( self, **kwargs ):
        Topo.__init__( self, **kwargs )
        s1 = self.addSwitch( 's1' )
        s2 = self.addSwitch( 's2' )
        self.addLink( s1, s1 )
```
### Actual Behavior:
running this topology leads to Exception Error creating interface pair 
```
root@portal:~/openflow_perf# python mn.py
*** Creating network
*** Adding controller
*** Adding hosts:

*** Adding switches:
s1 s2 
*** Adding links:
Traceback (most recent call last):
  File "mn.py", line 36, in <module>
    runTopo()
  File "mn.py", line 15, in runTopo
    net = Mininet( topo=topo )
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 174, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 502, in build
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 489, in buildFromTopo
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 400, in addLink
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 451, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 495, in makeIntfPair
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 195, in makeIntfPair
Exception: Error creating interface pair (s1-eth1,s1-eth1): RTNETLINK answers: File exists
```
If  self.addLink() contains different switches app runs as expected.

**Comment by ongrid** [comment]
Fixed in  PR #751
