### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/var/log/ryu/ryu.log'

### ISSUE THREAD

**Issue by liyinbest990** [mininet/mininet#791]
Hi all, 

I am new for Ryu. I installed Ryu in Ubuntu 16 by following https://github.com/osrg/ryu and 
https://github.com/osrg/ryu/wiki/OpenFlow_Tutorial. However, when I tried to run ryu-manager, I always got the following error: 

linux@linux-VirtualBox:~/ryu$ PYTHONPATH=. ./bin/ryu-manager ryu/app/simple_switch.py
Traceback (most recent call last):
  File "./bin/ryu-manager", line 19, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 68, in main
    log.init_log()
  File "/usr/lib/python2.7/dist-packages/ryu/log.py", line 79, in init_log
    disable_existing_loggers=False)
  File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python2.7/logging/handlers.py", line 391, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/var/log/ryu/ryu.log'

Does anyone help me to solve this problem? 

Thanks.

**Comment by laravich** [comment]
Hi, Did you get a solution for this? I am getting the same error.

**Comment by maborghe** [comment]
I solved this by installing RYU with 'pip install ryu' (I had installed it from source before)

**Comment by jruan123** [comment]
> Hi all,
> 
> I am new for Ryu. I installed Ryu in Ubuntu 16 by following https://github.com/osrg/ryu and
> https://github.com/osrg/ryu/wiki/OpenFlow_Tutorial. However, when I tried to run ryu-manager, I always got the following error:
> 
> linux@linux-VirtualBox:~/ryu$ PYTHONPATH=. ./bin/ryu-manager ryu/app/simple_switch.py
> Traceback (most recent call last):
> File "./bin/ryu-manager", line 19, in 
> main()
> File "/usr/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 68, in main
> log.init_log()
> File "/usr/lib/python2.7/dist-packages/ryu/log.py", line 79, in init_log
> disable_existing_loggers=False)
> File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig
> handlers = _install_handlers(cp, formatters)
> File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers
> h = klass(*args)
> File "/usr/lib/python2.7/logging/handlers.py", line 391, in **init**
> logging.FileHandler.**init**(self, filename, mode, encoding, delay)
> File "/usr/lib/python2.7/logging/**init**.py", line 913, in **init**
> StreamHandler.**init**(self, self._open())
> File "/usr/lib/python2.7/logging/**init**.py", line 943, in _open
> stream = open(self.baseFilename, self.mode)
> IOError: [Errno 2] No such file or directory: '/var/log/ryu/ryu.log'
> 
> Does anyone help me to solve this problem?
> 
> Thanks.

Hi, I have the same problem. But I figure it out. Could you check your ryu document location? You might download Ryu in ROOT. If you download in the root, first (sudo rm -rf ryu) to rm ryu from root. Then download again, do not download under root.

**Comment by cheriimoya** [comment]
soo, this is closed then, right?

**Comment by laravich** [comment]
yes
