### ISSUE TITLE
Error creating interface pair (s1-eth1,h1-eth0) in mininet

### ISSUE THREAD

**Issue by bmkourosh** [mininet/mininet#804]
I have created a custom topology as following and run it using mininet and connect to POX remote controller.

```
class CustomTopo (Topo):   
    def build(self):
        S1 = self.addSwitch('s1')
        H1 = self.addHost('h1')
        H2 = self.addHost('h2')
        self.addLink(S1, H1)
        self.addLink(S1, H2)

topo = CustomTopo()
net = Mininet(topo)
net.start()
topos = {'mytopo': CustomTopo}
```

It worked correctly first time, but after that I received following error in POX controller when it tried to add links:

**Caught exception. Cleaning up...
Exception: Error creating interface pair (s1-eth1,h1-eth0): RTNETLINK answers: File exists**

What can I do to solve it?

**Comment by Hrish1** [comment]
try running "sudo mn -c"

and then run the script.

**Comment by bmkourosh** [comment]
I already try it but it does not solve the problem.

**Comment by bmkourosh** [comment]
I found out that my topology create each host twice, so it can not add link between s1 and h1 for the second time. What do I have to do to solve it? any idea please???

**Comment by gabay** [comment]
@bmkourosh You did not attach the command line, but i guess it was something like this:
`sudo mn --custom custom.py --topo mytopo`

Note that you create a mininet network when mn imports your code (net = Mininet(topo), net.start())
After that - mn runs a mininet instance on its own, which collides with yours

Proposed solution: remove the following lines:
```
topo = CustomTopo()
net = Mininet(topo)
net.start()
```

**Comment by novakboskov** [comment]
`sudo mn -c` does not solve the problem in general.

I run my topologies in a loop from a shell script, the script executes `sudo mn -c` before each topology run. A few first iterations of the loop usually succeed, and then some subsequent iteration fails with an `Exception: Error creating interface pair (h2-eth0,s1-eth1): RTNETLINK answers: Operation not permitted `.

Here are the logs to prove that:
```
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_corelt-nox_core ovs-openflowd ovs-controllerovs-testcontroller udpbwtest mnexec ivs ryu-manager 2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl --timeout=1 list-br
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.

*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(50.00Mbit 10.0ms delay 0.50000% loss) (50.00Mbit 10.0ms delay 0.50000% loss) (h1, s1) Traceback (most recent call last):
  File "/home/storage/EXPERIMENTS/1/mininet_exec.py", line 159, in <module>
    main(p_args)
  File "/home/storage/EXPERIMENTS/1/mininet_exec.py", line 99, in main
    net = Mininet(topo=topo, host=CPULimitedHost, link=TCLink, autoStaticArp=True)
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/net.py", line 174, in __init__
    self.build()
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/net.py", line 502, in build
    self.buildFromTopo( self.topo )
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/net.py", line 489, in buildFromTopo
    self.addLink( **params )
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/net.py", line 400, in addLink
    link = cls( node1, node2, **options )
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/link.py", line 557, in __init__
    Link.__init__( self, *args, **kwargs)
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/link.py", line 450, in __init__
    self.makeIntfPair( intfName1, intfName2, addr1, addr2,
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/link.py", line 495, in makeIntfPair
    return makeIntfPair( intfname1, intfname2, addr1, addr2, node1, node2,
  File "/home/novak/.virtualenvs/an_env/lib/python3.9/site-packages/mininet/util.py", line 266, in makeIntfPair
    raise Exception( "Error creating interface pair (%s,%s): %s " %
Exception: Error creating interface pair (h2-eth0,s1-eth1): RTNETLINK answers: Operation not permitted 
```

Even worse, when I put the script to sleep for 5 seconds in between iterations, then it usually runs more iterations until it eventually fails with an `RTNETLINK answers: Operation not permitted `.

**Comment by hotelll** [comment]
@Hrish1 It works! But what is the use of this command?
