### ISSUE TITLE
RTNETLINK answers: File exists but link does not exist in the net.

### ISSUE THREAD

**Issue by luism6n** [mininet/mininet#810]
### Description

I'm trying to create this simple topology:

```json
{
  "nodes": [
    {
      "group": 10,
      "id": "h10"
    },
    {
      "group": 2,
      "id": "s20"
    },
    {
      "group": 2,
      "id": "s21"
    },
    {
      "group": 10,
      "id": "h30"
    }
  ],
  "links": [
    {
      "source": "s21",
      "target": "h10",
      "value": 10
    },
    {
      "source": "s20",
      "target": "h10",
      "value": 10
    },
    {
      "source": "s21",
      "target": "h30",
      "value": 10
    },
    {
      "source": "s20",
      "target": "s21",
      "value": 10
    },
    {
      "source": "s20",
      "target": "h30",
      "value": 10
    }
  ]
}
```

Below is the relevant part of the code and its output.

Code:

```python
net.link = TCULink
for l in network_graph['links']:
    u, v, link_speed = l['source'], l['target'], l['value']
    print u, v
    net.addLink(nodes[u], nodes[v], link_speed)
    print [str(l) for l in net.links]
```

Output:

```
mininet ~/host
$ sudo mn -c; sudo python main.py
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
<snip cleanup output>
*** Cleanup complete.
s21 h10
['s21-eth10<->h10-eth0']
s20 h10
['s21-eth10<->h10-eth0', 's20-eth10<->h10-eth1']
s21 h30
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    net.addLink(nodes[u], nodes[v], link_speed)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 366, in addLink
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 574, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 559, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 449, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/link.py", line 493, in makeIntfPair
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 194, in makeIntfPair
    
Exception: Error creating interface pair (s21-eth10,h30-eth0): RTNETLINK answers: File exists
```

### Expected/Desired Behavior:

The link should be created.

### Actual Behavior:

An error occurs.

### Detailed Steps to Reproduce the Behavior:

Just run the code in this Gist: https://gist.github.com/luism6n/ddbc3300789b2ddfe564daedfd186b47

### Additional Information:

```
mininet ~/host
$ sudo mn --version
2.2.2
mininet ~/host
$ python --version
Python 2.7.6
```

**Comment by luism6n** [comment]
I've solved it by not overwriting the default link constructor with:

`net.link = TCULink`

and instead adding links to the network using:

`net.addLink(nodes[u], nodes[v], cls=TCULink, bw=link_speed)`
