### ISSUE TITLE
Occasional exception on mn exit

### ISSUE THREAD

**Issue by lantz** [mininet/mininet#821]
### Expected/Desired Behavior:

exit without exception

### Actual Behavior:

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 89, in <lambda>
    atexit.register( lambda: write_history_file( history_path ) )
IOError: [Errno 22] Invalid argument
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-x86_64/egg/mininet/cli.py", line 89, in <lambda>
IOError: [Errno 22] Invalid argument

### Detailed Steps to Reproduce the Behavior:

1. probably remove the file at `history_path`
2. run mn and quit

**Comment by ramonfontes** [comment]
I noticed that issue when the number of lines in `.mininet_history` is >= 1000. I can solve it if I set the _history length_ to infinite `set_history_length( -1 )`. I'm not sure whether this is the best way to fix it though.

**Comment by DylanNS** [comment]
I having same error every time that I write some command at CLI and exit. I tried to set the history length to infinite, but don`t find the file "build/bdist.linux-x86_64/egg/mininet/cli.py" to edit it. The folder "/mininet/build/bdist.linux-x86_64" is empty. And when I edit the file "/mininet/mininet/cli.py", it appears to not have any effect which appears to be very strange to me once I wrote on my python script to import CLI from mininet.cli . @ramonfontes , Could you explain to me where I can find that file that you edit to fix the history_path problem ? Thanks in advance.

**Comment by ramonfontes** [comment]
[cli.py#L90](https://github.com/mininet/mininet/blob/cf6da391fa4a9271071dff59b41c9fe4e74277dd/mininet/cli.py#L90).

**Comment by ZhijiaCHEN** [comment]
Got the same error recently. @ramonfontes 's fix actually tells what the problem is (thank you!), the mininet command history is accumulated to more than 1000 lines. Maybe a cleaner way is to clear the content of `~/.mininet_history`.

**Comment by lantz** [comment]
Yes this is annoying; would anyone like to submit a fix?
