### ISSUE TITLE
cgcreate: can't create cgroup /receiver: Cgroup, operation not allowed

### ISSUE THREAD

**Issue by miqianmimi** [mininet/mininet#860]
```
Traceback (most recent call last):
  File "small-queue.py", line 203, in <module>
    simpleRun()
  File "small-queue.py", line 96, in simpleRun
    net = Mininet(topo=topo, host=CPULimitedHost, link=TCLink)
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 172, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 442, in build
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 413, in buildFromTopo
  File "build/bdist.linux-x86_64/egg/mininet/net.py", line 224, in addHost
  File "build/bdist.linux-x86_64/egg/mininet/node.py", line 647, in __init__
  File "build/bdist.linux-x86_64/egg/mininet/util.py", line 127, in errFail
Exception: errFail: ('cgcreate -g cpu,cpuacct,cpuset:/receiver',) failed with return code 87: cgcreate: can't create cgroup /receiver: Cgroup, operation not allowed
```

when i am not us vm .

**Comment by soreana** [comment]
Could you attach your code? How can I reproduce this error ?

**Comment by Layman98** [comment]
Have you solved this problem? I've got the same error while running mininet (creating a topology?).

**Comment by miqianmimi** [comment]
no

**Comment by miqianmimi** [comment]
Exception: errFail: ('cgcreate -g cpu,cpuacct,cpuset:/sender',) failed with return code 87: cgcreate: can't create cgroup /sender: Cgroup, operation not allowed

**Comment by lantz** [comment]
Can you confirm that:

1) `cgcreate -g cpu,cpuacct,cpuset:/sender` works properly
2) the problem occurs in a standart Mininet VM

Thanks.
