### ISSUE TITLE
Install fail on fedora 31

### ISSUE THREAD

**Issue by learnuxme** [mininet/mininet#942]
Hey guys, I tried installing on a Fedora 31 unsuccessfully... Hope this helps and maybe you can give me some clues as to what I need to do to get to my instaling mininet:

### Expected/Desired Behavior:
flawless install of mininet 

### Actual Behavior: 
SyntaxError: invalid syntax
make: *** [Makefile:52: install] Error 1

### Detailed Steps to Reproduce the Behavior: 
install.sh -fnpv

### Additional Information:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    from mininet.net import VERSION
  File "/home/learnux/mininet/mininet/net.py", line 99, in <module>
    from mininet.cli import CLI
  File "/home/learnux/mininet/mininet/cli.py", line 181
    except Exception, e:
                    ^
SyntaxError: invalid syntax
make: *** [Makefile:52: install] Error 1

System was up to date before install attempt.
Feel free to contact me if more information is necessary.
Thanx.

**Comment by JuFil** [comment]
Hi learnuxme!

What version of mininet? Do you use the latest version of this repo?
Could you upload the entire output of install.sh?
Including the output on stderr:
`./install.sh -fnpv  > log 2>&1`

Best regards

**Comment by JuFil** [comment]
That said, it looks like an issue with python2 vs python3.
`except Exception, e` is only allowed in python2, not python3.

**Comment by learnuxme** [comment]
> Hi learnuxme!
> 
> What version of mininet? Do you use the latest version of this repo?
> Could you upload the entire output of install.sh?
> Including the output on stderr:
> `./install.sh -fnpv > log 2>&1`
> 
> Best regards

Hi Jufil, to give you a quick reply: I am trying to install what seems to me like the latest stable versionof mininet, version 2.2.2, and have the latest version of python available on Fedora 31, which is 3.7.
Also, being just a noob apprentice sysadmin I did not achive the command you suggested I did(./install.sh -fnpv > log 2>&1), sorry.

**Comment by JuFil** [comment]
I see, no worries!

Did you install mininet from the Package repo? Then you do not need to install it by install.sh any more.
However, that version is relatively old and does not work with python3 (thus the error).
You can check if its installed by "mn -version".
Then make sure, that your `python` interpreter has version 2.7: `python -V` should print somthing like 2.7.16
Depending on your use case, this might be sufficient. Then, you can only import it by the python2 interpreter.

Personally, I would recommend you to uninstall the version from the package repo (`dnf remove mininet`) and install it from this git Repo so you have the latest version.
If you want to install it for python3, specify it like so: `PYTHON=python3 ./install.sh -fnv`

I think, you do not require the -p flag for now, so you can try executing install.sh without it.

I don't really use fedora, so I'm not perfectly sure how the package manager handles the different python versions.

Best regards

**Comment by learnuxme** [comment]
Hi JuFil,
I actually installed version 2.2.2 from this git repo, and since install failed and I seem to have Python 3.8.2, I will retry including the python argument you suggested...

**Comment by learnuxme** [comment]
... Failed.
pyflake and pep8 missing. Installed them and now openflow is blocking the install:
"fatal: destination path 'openflow' already exists and is not an empty directory."
Although I deleted the entire folder...
Coming to think of it, could it be useful to write an entire process on how to instll mininet for Fedora? Which packages need to be installed as prerecquisite, etc?
Shoud I contact the dev team?
...Or am I just the biggest dumbest noob ever?

**Comment by learnuxme** [comment]
And thank you so much for your help, JuFill.
I am not giving up, I will succeed and install a fully functionnal mininet on my Fedora, now running version 32.

**Comment by JuFil** [comment]
Hi learnuxme,

that install.sh has the exact purpose to install all prerecquisites and do everything needed to install mininet.

1st: Version 2.2.2 **does not** work with python3. If you want to install it with 2.2.2, you'll need to install it with python2. So make sure that your Python executable has version 2, hence `python --version` prints  "Python 2.7.X". I do not know how Fedora handles different python interpreters, maybe you need to use `python2`, then you need to execute `PYTHON=python2 ./install.sh..`

2nd: Is there a specific reason why you need version 2.2.2? I assume it would be more convenient to use the current version, hence the current version of the master branch.

3rd: That says that the build directory was not cleaned. In the current version, the build dir is defined by:
```# Get directory containing mininet folder
MININET_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd -P )"

# Set up build directory, which by default is the working directory
#  unless the working directory is a subdirectory of mininet,
#  in which case we use the directory containing mininet
BUILD_DIR="$(pwd -P)"
case $BUILD_DIR in
  $MININET_DIR/*) BUILD_DIR=$MININET_DIR;; # currect directory is a subdirectory
  *) BUILD_DIR=$BUILD_DIR;;
esac
```
IMHO, the install script is not perfect. I might issue a PR to improve the install.sh to eliminate such inconveniences.

4th: Try to perform the phases one-by-one. Hence, run `./install.sh -f`, then `./install.sh -n`, and `./install.sh -v`

I hope I could help

Best regards

**Comment by learnuxme** [comment]
Hi JuFill,
Do not hope, you can rest assured you are being of GREAT help, and I cannot thank you enough for this time you spend on me.
Following you advice, I removed the openflow and mininet directories from the 2.2.2 install script, then attempted an install from 2.3.0d6 (my mistake, seeing this "d6" suffix tricked into thinking it was some beta version). I also followed your advice and started intalling each package separately:
./install.sh -f: worked like a charm!
./install.sh -v:  no success with the error message:
No match for argument: openvswitch-controller
BUT I found a workaround: installed the appropriate openvswitch-devel package.
./install.sh -n: unsuccessful... Failing in installing dependencies:
No match for argument: pyflakes
Package pylint-2.4.4-3.fc32.noarch is already installed.
No match for argument: python-pep8
Package python3-pexpect-4.7.0-5.fc32.noarch is already installed.
although, I made sure to have the latest 2.2.0 pyflakes packages.
Any clues?
Thanx to your assistance, I am getting there. Will look into it and try and solve this on my own, but don't hesitate to get back to me if any tips on solving this issue.
Thank you so much again.
Regards

**Comment by adrianomarto** [comment]
Hi @learnuxme,
I created the pull request #1003 to make the installation work on Fedora 32. I did some quick tests, and it seems to work. I would appreciate if you could take a look and provide some feedback.
Regards,
Adriano.
